feat(fetch): fetch all challenge inputs

diff --git a/aoc b/aoc
--- a/aoc
+++ b/aoc
@@ -1,12 +1,10 @@
 #!/usr/bin/env bash
 
-set -u
-
 ###############################################
 #   VERSION INFORMATION                       #
 ###############################################
 
-AOC_VERSION="v2.0.0"
+AOC_VERSION="v2.1.0"
 
 usage() {
     echo "Usage: $(basename $0) COMMAND YEAR DATE"
@@ -69,6 +67,23 @@ debug() {
 #   UTILITIES                                 #
 ###############################################
 
+validate() {
+    local year="$1"
+    local day="$2"
+
+    # Get current
+    read cur_year cur_month cur_day <<<"$(date '+%Y %-m %-d')"
+
+    # Validate year
+    ((year > 2015)) || fatal "before AoC: $year"
+    ((cur_month != 12 && year == cur_year)) && fatal "AoC hasn't started: $year"
+    ((year <= cur_year)) || fatal "in the future: $year"
+
+    # Validate day
+    ((day > 0 && day < 26)) || fatal "invalid day: $day"
+    ((year == cur_year && day <= cur_day)) || fatal "AoC day not live: $day"
+}
+
 # Get the root of the repository using a series of ordered metrics.
 get-root() {
     local -a precedence=(.git .gitignore README.md)
@@ -107,6 +122,7 @@ aoc-lang() {
     # Globals
     declare -g YEAR="$2"
     declare -g DATE=$(printf "%02d" "$3")
+    validate "$YEAR" "$DATE"
 
     # Run the language-specific compiler
     local lang="$1"
diff --git a/utils/aoc-fetch b/utils/aoc-fetch
--- a/utils/aoc-fetch
+++ b/utils/aoc-fetch
@@ -1,7 +1,5 @@
 #!/usr/bin/env bash
 
-set -eu
-
 ###############################################
 #   USAGE                                     #
 ###############################################
@@ -33,14 +31,74 @@ fatal() {
     exit 1
 }
 
+warning() {
+    echo -e "[\033[33m*\033[0m] $(basename ${BASH_SOURCE[0],,}): $1"
+}
+
 debug() {
     (($DEBUG == 1)) || return 0
-    echo -e "[\033[32m+\033[0m] $1"
+    echo -e "[\033[32m+\033[0m] $(basename ${BASH_SOURCE[0],,}): $1"
 }
 
 ###############################################
 #   DRIVERS                                   #
 ###############################################
+
+fetch() {
+    local year="$1"
+    local date="$2"
+    validate "$year" "$date"
+    debug "Fetching: ${year@A} ${date@A}"
+
+    # Get AOC_TOKEN from environment
+    source utils/aoc-session || true
+    [[ -n "$AOC_SESSION" ]] || fatal "missing AOC_SESSION env"
+
+    # Output location
+    local outfile=input/"$year"/day-"$(printf "%02d" "$date")".txt
+    if [[ -f "$outfile" ]]; then
+        warning "file exists: $outfile"
+        return
+    fi
+
+    # cURL the contents
+    tmpfile=$(mktemp)
+    curl -sS --fail-with-body \
+        -H "Cookie: session=$AOC_SESSION" \
+        -H "User-Agent: heavycircle (+https://github.com/heavycircle)" \
+        "https://adventofcode.com/$year/day/$date/input" -o "$tmpfile"
+
+    # Copy on success
+    if (($? == 0)); then
+        mkdir -p "$(dirname "$outfile")"
+        mv "$tmpfile" "$outfile"
+
+        DEBUG=1 debug "file retrieved: $outfile"
+    else
+        warning "could not retrieve file"
+    fi
+
+}
+
+fetch-all() {
+    # Get current month
+    read cur_year cur_month cur_day <<<"$(date '+%Y %-m %-d')"
+    local last_day=25
+
+    # Get ending values
+    if ((cur_month == 12)); then
+        last_day="$cur_day"
+    else
+        ((--cur_year))
+    fi
+
+    # Iterate
+    for ((year = 2015; year <= cur_year; year++)); do
+        for ((day = 1; day <= last_day; day++)); do
+            fetch "$year" "$day"
+        done
+    done
+}
 
 main() {
     local -a positional
@@ -64,28 +122,20 @@ main() {
 
     # Positional arguments
     set -- "${positional[@]}"
-    (($# == 2)) || fatal "incorrect argument count!"
+    (($# < 3)) || fatal "incorrect argument count!"
     local year="$1"
     local date="$2"
 
-    debug "Fetching: ${year@A} ${date@A}"
+    if [[ "$year" == "all" ]]; then
+        # Fetch all
+        fetch-all
+    elif [[ -n "$date" ]]; then
+        # Fetch the specific ref
+        fetch "$year" "$date"
+    else
+        fatal "missing argument: date"
+    fi
 
-    # Get AOC_TOKEN from environment
-    source utils/aoc-session || true
-    [[ -n "$AOC_SESSION" ]] || fatal "missing AOC_SESSION env"
-
-    # Output location
-    local outfile=input/"$year"/day-"$(printf "%02d" "$date")".txt
-    [[ -f "$outfile" ]] && fatal "file exists: $outfile"
-    mkdir -p "$(dirname "$outfile")"
-
-    # cURL the contents
-    curl -sS --fail-with-body \
-        -H "Cookie: session=${AOC_SESSION}" \
-        -H "User-Agent: heavycircle (+https://github.com/heavycircle)" \
-        "https://adventofcode.com/$year/day/$date/input" -o "$outfile"
-
-    DEBUG=1 debug "file retrieved: $outfile"
 }
 
 main "$@"
